### ISSUE TITLE
Find steam using registry or at least winapi calls

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Vive#6]
Right now we have hard-coded two possible install paths, but that's fairly fragile: https://github.com/OSVR/OSVR-Vive/blob/master/FindDriver.cpp#L85

Won't work on any system where Windows or Steam isn't installed on C in the default location, or where a localized non-English version of Windows is being used.

I imagine there's probably a registry key to locate Steam, and failing that, we can at least get the location of the "special directory" 32-bit program files from windows API.

**Comment by rpavlik** [comment]
We may actually be able to do it using a config file that points to the config files - the user path appears to be:

- `%LOCALAPPDATA%\openvr\openvrpaths.vrpath`
- `~/.openvr/openvrpaths.vrpath` on at least Mac (probably on Linux too)

and that's a nice little JSON file that contains data that we get from vrpathreg + more - on Windows for me, it shows:

```json
{
   "config" : [ "C:\\Program Files (x86)\\Steam\\config" ],
   "external_drivers" : null,
   "log" : [ "C:\\Program Files (x86)\\Steam\\logs" ],
   "runtime" : [
      "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR\\",
      "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR"
   ]
}
```

Might involve a little bit of re-structuring of the file-finding, but this seems a lot less fragile than parsing the output of vrpathreg.

**Comment by godbyk** [comment]
For comparison, here's what `~/.openvr/openvrpaths.vrpath` looks like on my Mac:

```json
{
	"runtime" : [ "/Users/kevin/Library/Application Support/Steam/steamapps/common/SteamVR" ],
	"config" : [ "/Users/kevin/Library/Application Support/Steam/config" ],
	"log" : [ "/Users/kevin/Library/Application Support/Steam/logs" ]
}
```

**Comment by d235j** [comment]
@rpavlik @godbyk this is how the library that's part of the OpenVR client SDK finds the SteamVR install path and starts the vrserver.

**Comment by rpavlik** [comment]
also have untested code for mac and linux based on your info in now. (Still missing the code to do the dynamic loading)

**Comment by godbyk** [comment]
Can't you just reuse code from libfunctionality?

**Comment by rpavlik** [comment]
Or at least copy it, yes, think so, though there is the bit about extending the library search path that is required, I think

**Comment by rpavlik** [comment]
(would make a nice pull request!)
